modLoader="javafml"
loaderVersion="[3,)"
issueTrackerURL="https://github.com/Mrbysco/SpellChecker/issues"
license="LGPL-3.0"

[[mods]]
modId="spellchecker"
version="${file.jarVersion}"
displayName="Spell Checker"
displayURL="https://www.curseforge.com/minecraft/mc-mods/spell-checker"
authors="Mrbysco"
description='''
Need your spelling checked?
'''
logoFile="logo.png"

[[dependencies.spellchecker]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.6,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.spellchecker]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.6.12-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="spellchecker.mixins.json"